---
apiVersion: v1
kind: Service
metadata:
  name: go-example
  labels:
    app: go-example
spec:
  selector:
    app: go-example
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
