---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example
  labels:
    app: go-example
spec:
  selector:
    matchLabels:
      app: go-example
  template:
    metadata:
      labels:
        app: go-example
    spec:
      containers:
        - name: go-example
          image: lnkphm/go-example:latest
          imagePullPolicy: Always
